pybb/models.py
pybb/tests.py
pybb/views.py
test/test_project/templates/404.html

When a topic is created, it's in two step :
* topic creation (`updated` field is None at this moment)
* then, post creation
* topic update : `post_count` and `updated` fields
* forum update
A use was able to display the topic detail page between those 2 steps and had a topic without post. It the template tag "pybb_topic_unread" was called after this display but before the second step of topic creation, an exception was raised `can't compare datetime.datetime to NoneType` because topic 's `updated` field is still `None`
This pull add two changements :
* A topic detail now raise a 404 if the topic is not yet fully created (mean : has not yet post_count greater than 0)
* The topic's `updated` field is now set with the `created` field. This correction is not necessary because of the first …

topic without post during a really short time 

---

pybb/templates/pybb/avatar.html

Fixes #171 but leaves #160.  I am inclined to agree with @GeyseR that file deletion should be left to the implementer.  There are so many ways of storing static files, filesystem, s3, mongo, etc.  I suppose you could implement it for the default avatar field in PybbProfile, but I don't know how many people will be using the default profile without overriding it, and off the top of my head I don't know how you would check for that.

Easy thumbnails fix

---

pybb/templatetags/pybb_tags.py

In python 3 range is now a generator (like xrange was - there is no xrange in python 3)
Currently this throws an TypeError unsupported operand + for type and list
Casting range to a list works for both python 2 and 3

Fix python 3 bug

---

pybb/tests.py

There are sleep statements in some of the early tests. They were necessary to account for the fact that until recently [MySQL backends did not store <1second resolution for DateTimeFields](https://code.djangoproject.com/ticket/19716).
In this PR I have chosen to just skip the tests using `@skipUnlessDBFeature('supports_microsecond_precision')`.  This is because, unless you are going to somehow convince end-users to not post within 1 second of each other, the test is not realistic anyway.
However, it would be possible to re-add these tests, with sleep statements, for MySQL backends only, using `@skipIfDBFeature`

Remove sleep statements in tests (saves about 10-15 mins on travis, about a minute or two locally)

---

pybb/views.py

By requesting a list of an admin users topics, unauthenticated users can see a list of hidden topics.

Fix incorrect permissions check in UserTopics view

---

pybb/templates/pybb/_markitup.html
pybb/templates/pybb/add_post.html
pybb/templates/pybb/edit_post.html
pybb/templates/pybb/post_form.html
pybb/templates/pybb/post_template.html
pybb/templates/pybb/topic.html
test/test_project/test_project/settings.py

As far as I can tell, it's generally preferred to use staticfiles and
{%static 'relative-filepath' %} instead of using STATIC_URL.
In my Django 1.8 project, I didn't get the static context handler by default.
This resulted in a good bit of digging around before I found out what was
causing STATIC_URL to be undefined.
The Django documentation on static file handling in templates doesn't
even mention using STATIC_URL anymore - it looks like Django 1.4 was the
last version that had documentation showing this usage:
https://docs.djangoproject.com/en/1.4/howto/static-files/
I've also gone ahead and removed context_processors.static and added
django.contrib.staticfiles to the installed apps in the project settings.py.

Templates should use staticfiles, not STATIC_URL

---

pybb/util.py

django.utils.importlib was deprecated in Django 1.7 and removed in 1.9.
This PR updates the import as per Django's recommendation: https://docs.djangoproject.com/en/1.8/releases/1.7/#django-utils-dictconfig-django-utils-importlib

Use Python stdlib version of importlib instead of deprecated django.utils.importlib

---

pybb/views.py

This change is needed for PyBBM to work on Django 1.9. 
django.forms.utils is removed in Django 1.9. Details: https://docs.djangoproject.com/en/1.9/releases/1.9/

Use django.forms.utils for Django 1.9 compatibility.

---

pybb/permissions.py

It's definition in permissions.py is wrong, as it accepts a topic (and is
passed them in views.py) but stores them in "forum". This changes the
parameter name from "forum" to "topic".

may_subscribe_topic is passed topics, not forums.

---

pybb/templates/pybb/index.html

Hyperlinks "Last updates in topics" and "Mark all forums as read" were displayed next to each other without any space between them (the space was a part of the first hyperlink) making it hard to distinguish one from another.
Screenshot:
After this change, the space is no longer a part of the hyperlink and a slash has been inserted between the hyperlinks (for consistency with topic.html: Stick topic / Close topic / Admin / Subscribe).

Separated hyperlinks that had no space between them in index template.

---

pybb/compat.py
pybb/migrations/0005_auto_20151108_1528.py
pybb/models.py

Not every Django project environment has Pillow installed and some forum installations may not use avatars at all.
Also fixed 'null has no effect on ManyToManyField' error when pybb.models.Forum.moderators field is initialized.

Allow to use pybbm without Pillow and fixes ManyToManyField warning

---

pybb/admin.py
pybb/forms.py
pybb/permissions.py
pybb/templates/pybb/edit_privileges.html
pybb/templates/pybb/user.html
pybb/tests.py
pybb/urls.py
pybb/views.py

The only way to add a moderator is to add a user id to the forum's moderator list in the django admin which is not an easy method for lambda users.
It also has the issue to make you go through all the forums to a add the same moderator.
That pull adds a form accessible from a user profile to grant him moderator privileges:
* It adds a new permission may_manage_forum that checks if a user has change_forum permission.
* Before displaying it checks the permission on every forum, so it adds the possibility to have different permissions on every forum.
* It allows you to add/remove a moderator to multiple forums in a few clicks

New feature + tests: Grant moderator privileges form

---

.travis.yml
docs/problems.rst
pybb/tests.py
test/test_project/test_project/settings.py
tox.ini

With a DB (like MySQL) which does not support microseconds, we force
a 1 second sleep for some operations to avoid failures for some tests which
require a different datetime between two operations.  
It adds few seconds to run the test suite with mysql but it run all
tests (there were some tests which were skipped for mysql)
This commit allow to run test with sqlite, mysql or postgres
with tox for local testing.
Also fix travis issues:
* mysql has gone away
* only create DBs if required
Add methods `create_post` and `create_post_via_http` in `tests.py` to simplify tests creation.
Add a "problems" section in the doc about using DBs without microseconds
support to explain what are the side-effects.

Allow ALL tests to be runned with all DB

---

pybb/migrations/0007_auto_20170111_1504.py
pybb/models.py

* `topic.updated` is used when using "first-unread" and should be used when creating a "last activity" topic for a website. DB index has been added.
* `topic.created` is used as the default sort order of topic via Meta.ordering. DB index has been added.
* `post.updated` should be used when using a search index app (django-haystack for exemple) to reindex only the updated topics. DB index has been added.

add missing indexes

---

pybb/tests.py
pybb/views.py

Two reasons for moving the method call:
1. I wouldn't expect 'get_context_data' to have side effects.
2. It ensures that the view returns without error before marking the topic read
This PR also modifies an inefficient query in `mark_read` that checks for unread topics in forum.

Move 'mark_read' call out of 'get_context_data' and into 'get'.

---

docs/problems.rst
pybb/tests.py

There was a merged PR (#197) with some read-tracking modifications which needed a little adjustment to work with another merged PR (#258)
This PR fixes this conflict.

fix mysql test error because of PR merges

---

test/test_project/test_project/settings.py

related to https://github.com/hovel/pybbm/pull/262#issuecomment-278853942
Now, django is aware of timezone when running tests and whatever the server TZ is, datetime operations are now correct :)
Thanks @lampslave for pointing this.

fix TIME_ZONE errors for datetime tests

---

pybb/forms.py
pybb/models.py
pybb/templates/pybb/move_post.html
pybb/templates/pybb/post_template.html
pybb/templatetags/pybb_tags.py
pybb/tests.py
pybb/urls.py
pybb/views.py
test/test_project/test_project/settings.py
tox.ini

This PR is related to #57 and #219 . It's done with #262 which is required.
It adds a button "move" on each post for moderators. Moving the first post of the topic, move the entire topic. Moving a following post allow moderator to move all following post or just some post into a new topic (which can be in another forum).
#219 is not really done in this PR : we can not move posts into an **existing** topic because :
* selecting the existing topic is painfull. We could add a dependency to select2 (for eg.) to have
a usable topic input to list existing topics and allow auto complete. Or we could save in session
selected posts to move, and have a "paste selected posts" button in a topic... Or maybe find
another solution. In any case, choosen solution will have advantages and disadvantages …

Move topic and split posts

---

.travis.yml

Coveralls now runs only for Python 2.7 + Postgres + Django LTS (1.8)
(it was running only for postgres + django 1.8 but for all python versions)

fix travis to run coveralls only once

---

pybb/signals.py

As per [Django docs](https://docs.djangoproject.com/en/2.0/ref/signals/#post-save), applications should not modify the database in `post_save` signal handlers, as the database might not be in a consistent state yet. In practise, doing so in pybb makes it impossible to use dumpdata/loaddata commands.
1. create django project with pybb, using custom UserProfile as profile model 
2. export data with `manage.py dumpdata`
3. try to load this data again with `manage.py loaddata`
Doing so will cause an `IntegrityError` in step 3, since when the saved User model gets loaded, the signal handler will create a UserProfile instance, and when the UserProfile instance gets loaded later on,  unique constraint will fail.
Solution: don't create or update profile when signal is triggered from fixture load

disable post_save handling on fixture load

---

docs/contributing.rst
docs/customuser.rst
docs/install.rst
docs/notifications.rst
docs/settings.rst
docs/templatetags.rst
docs/testing.rst
docs/updates.rst
pybb/compat.py
pybb/forms.py
pybb/models.py
pybb/tests.py

There are small typos in:
- docs/contributing.rst
- docs/customuser.rst
- docs/install.rst
- docs/notifications.rst
- docs/settings.rst
- docs/templatetags.rst
- docs/testing.rst
- docs/updates.rst
- pybb/compat.py
- pybb/forms.py
- pybb/models.py
- pybb/tests.py
Fixes:
- Should read `splitted` rather than `splited`.
- Should read `environment` rather than `environnement`.
- Should read `overridden` rather than `overrided`.
- Should read `example` rather than `exemple`.
- Should read `standard` rather than `standrard`.
- Should read `should` rather than `shoud`.
- Should read `performance` rather than `perfomance`.
- Should read `inherit` rather than `inherite`.
- Should read `assignment` rather than `assigment`.
- Should read `symbols` rather than `sybmols`.
- Should read `subscribers` …

docs: Fix a few typos

---

pybb/admin.py
pybb/apps.py
pybb/compat.py
pybb/feeds.py
pybb/forms.py
pybb/models.py
pybb/profiles.py
pybb/templatetags/pybb_tags.py
pybb/urls.py
pybb/util.py
pybb/views.py
test/example_bootstrap/example_bootstrap/urls.py
test/example_thirdparty/example_thirdparty/urls.py
test/test_project/test_app/apps.py
test/test_project/test_project/urls.py

`ugettext`, `ugettext_lazy`, `force_str`, `smart_str` and `url` were removed in Django 4.0. This patch replaces them with their up-to-date counterparts, allowing to run PyBBM with Django 4.0+

Django 4.0 compatibility patches
